### ISSUE TITLE
Create IBM Account and Invite Team

### ISSUE THREAD

**Issue by Nathan-Silverglate** [SternDevops-Spring22-Inventory/inventory#12]
As a development team
We need access to IBM Cloud account
So that people can deploy to the cloud

Assumptions:

We will use IBM Cloud
We wish push manually just to make sure it works in IBM Cloud

 
 ```

**Comment by richlisi** [comment]
- Create a Python Flask Cloud Foundry application in IBM Cloud - US South.

-Naming is very important so please follow the following format: **nyu-inventory-service-sp2022**
